### ISSUE TITLE
Background Geolocation stop working after 5 minutes

### ISSUE THREAD

**Issue by ghimarcos** [capacitor-community/background-geolocation#71] opened 2022-07-25 13:31 UTC
Hi, i have a problem with background geolocation, it works perfectly for 5 minutes, after that it simply stops sending the POST with the location to my API.
I configure distanceFilter to send POST every 100 meters, it's looking like a limitation of foreground service, or bad configuration on my part. 

Link android limitation -> https://developer.android.com/about/versions/oreo/background?hl=en-US

I tested it on 3 different devices, 2 with android 11, and 1 with android 9, but same problem.

code example app.component.ts : 

-----------------------------------------------------------------------------------------------------------------------------------------
     this.watcher_id = BackgroundGeolocation.addWatcher(
          {
            backgroundMessage: "Cancel to prevent battery drain.",
            backgroundTitle: "Tracking You.",
            requestPermissions: true,
            stale: false,
            distanceFilter: 100
          },
          function callback(location, error) {
            if (error) {
              if (error.code === "NOT_AUTHORIZED") {
                Modals.confirm({
                  title: "Location Required",
                  message: (
                    "This app needs your location, " +
                    "but does not have permission.\n\n" +
                    "Open settings now?"
                  )
                }).then(function ({ value }) {
                  if (value) {
                    BackgroundGeolocation.openSettings();
                  }
                });
              }
              return console.error(error);
            }
            if (window.navigator.onLine) {
              //***  SENDING POST HERE
            }
          }
        );
-----------------------------------------------------------------------------------------------------------------------------------------

Exemple Android Manifest : 

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <application

          <service
            android:name="com.equimaps.capacitor_background_geolocation.BackgroundGeolocationService"
            android:enabled="true"
            android:exported="true"
            android:foregroundServiceType="location" />
    </application>

    
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-feature android:name="android.hardware.location.gps" />
</manifest>
-----------------------------------------------------------------------------------------------------------------------------------------

**Comment by diachedelic** [comment] 2022-07-26 00:44
Duplicate of #14.

**Closed by diachedelic** 2022-07-26 00:44 UTC
