### ISSUE TITLE
Save Battery - Check location every X seconds

### ISSUE THREAD

**Issue by Callan003** [capacitor-community/background-geolocation#43] opened 2021-12-08 13:48 UTC
**Is your feature request related to a problem? Please describe.**
The background geolocation drains too much battery.

**Describe the solution you'd like**
I would like to have an option to check the background geolocation every X seconds in order to save battery.

Is there any way I can achieve this? Is there any way I can make the plugin drain less battery power? Am I missing something?

Thank-you!

**Comment by Flaviu989** [comment] 2021-12-08 14:05
I think that would be useful to know, if it's possible.

**Comment by diachedelic** [comment] 2021-12-08 23:14
This looks like a duplicate of #34. Can you please describe your use case there?

**Closed by diachedelic** 2021-12-08 23:14 UTC
