### ISSUE TITLE
Send location  every X second

### ISSUE THREAD

**Issue by ivinantony** [capacitor-community/background-geolocation#83] opened 2022-11-16 12:14 UTC
I need to sent the location in every X second to the server. How can I implement this using this plugin.
Anyone have an idea about this?

**Comment by alindzon** [comment] 2022-12-12 04:54
try my fork i added a parameter for delay between readings.  Read next issue.

**Comment by diachedelic** [comment] 2023-03-19 02:24
Duplicate of #34.

**Closed by diachedelic** 2023-03-19 02:24 UTC
